// Generated by CoffeeScript 1.6.3
(function() {
  var click, cycleImages, getConfidence, makeJudgement, smileCb;

  $(function() {
    var el, elephants, sd;
    elephants = ['images/elephant1.jpg', 'images/elephant2.jpg', 'images/elephant1.jpg', 'images/elephant2.jpg'];
    el = $('#photocatch');
    el.photobooth();
    el.on("image", function(event, dataUrl) {
      return localStorage.setItem("imageData", dataUrl);
    });
    sd = new SmileDetector("vid");
    sd.onSmile(smileCb);
    sd.start(500);
    return cycleImages(elephants);
  });

  cycleImages = function(images) {
    var callback, timeoutID;
    $(".elephants .target").attr('src', images[0]);
    images = images.slice(1).concat([images[0]]);
    callback = function() {
      return (function(images) {
        return cycleImages(images);
      })(images);
    };
    return timeoutID = window.setTimeout(callback, 4000);
  };

  click = function() {
    return $(".trigger").trigger("click");
  };

  smileCb = function(isSmile) {
    var imgURL, lastIMG;
    imgURL = $(".elephants .target").attr('src');
    lastIMG = localStorage.getItem("currentImage");
    localStorage.setItem("LastImage", lastIMG);
    localStorage.setItem("currentImage", imgURL);
    click();
    if (lastIMG !== imgURL) {
      makeJudgement();
      localStorage.setItem("currentImageLikes", 0);
      localStorage.setItem("currentImageDislikes", 0);
    }
    if (isSmile) {
      $(".smile").removeClass("sad");
      $(".smile").addClass("happy");
      localStorage.setItem("currentImageLikes", parseInt(localStorage.getItem("currentImageLikes") + 1));
    } else {
      localStorage.setItem("currentImageDislikes", parseInt(localStorage.getItem("currentImageDislikes")) + 1);
      $(".smile").removeClass("happy");
      $(".smile").addClass("sad");
    }
    return $('.confidence').text("P(like)=" + getConfidence());
  };

  makeJudgement = function() {
    var conf, dataUrl, el, elephant;
    conf = getConfidence();
    el = conf > 0.49 ? ".likes" : ".dislikes";
    dataUrl = localStorage.getItem("imageData");
    elephant = $(".elephants .target").attr('src');
    return $("<div class='row'>").append('<img src="' + dataUrl + '" class="col-lg-6" >').append('<img src="' + elephant + '"  class="col-lg-6" width="200px" height="200px" >').prependTo(el);
  };

  getConfidence = function() {
    var conf, dislikes, likes;
    likes = parseInt(localStorage.getItem("currentImageLikes"));
    dislikes = parseInt(localStorage.getItem("currentImageDislikes"));
    conf = likes / (likes + dislikes);
    return conf;
  };

}).call(this);
