// Generated by CoffeeScript 1.6.3
(function() {
  var click, cycleImages, getConfidence, getTotal, makeJudgement, smileCb;

  $(function() {
    var checkFlickr, el, elephants, startSmiles;
    elephants = ['images/elephant1.jpg', 'images/elephant2.jpg', 'images/elephant1.jpg', 'images/elephant2.jpg'];
    el = $('#photocatch');
    el.photobooth();
    el.on("image", function(event, dataUrl) {
      return localStorage.setItem("imageData", dataUrl);
    });
    checkFlickr = function() {
      var a;
      if (photostream[0]) {
        return startSmiles();
      } else {
        console.log("Flickr not yet loaded");
        return a = window.setTimeout(checkFlickr, 1000);
      }
    };
    checkFlickr();
    return startSmiles = function() {
      var sd;
      sd = new SmileDetector("vid");
      sd.onSmile(smileCb);
      sd.start(500);
      return console.log("started");
    };
  });

  cycleImages = function(images) {
    var callback, timeoutID;
    $(".elephants .target").attr('src', images[0]);
    images = images.slice(1).concat([images[0]]);
    callback = function() {
      return (function(images) {
        return cycleImages(images);
      })(images);
    };
    return timeoutID = window.setTimeout(callback, 4000);
  };

  click = function() {
    return $(".trigger").trigger("click");
  };

  smileCb = function(isSmile) {
    var id, imgURL, lastIMG, oldID;
    id = getID();
    imgURL = photostream[id].src.replace("_z", "_s");
    lastIMG = localStorage.getItem("currentImage");
    if (imgURL !== lastIMG) {
      oldID = id > 0 ? id - 1 : 0;
      localStorage.setItem("LastImage", photostream[oldID].src.replace("_z", "_s"));
      localStorage.setItem("currentImage", imgURL);
      makeJudgement();
      localStorage.setItem("currentImageLikes", 0);
      localStorage.setItem("currentImageDislikes", 0);
    }
    if (isSmile) {
      $(".smile").removeClass("sad");
      $(".smile").addClass("happy");
      localStorage.setItem("currentImageLikes", parseInt(localStorage.getItem("currentImageLikes") + 1));
    } else {
      localStorage.setItem("currentImageDislikes", parseInt(localStorage.getItem("currentImageDislikes")) + 1);
      $(".smile").removeClass("happy");
      $(".smile").addClass("sad");
    }
    if (getTotal() === 2) {
      click();
    }
    return $('.confidence').text("P(like)=" + getConfidence());
  };

  makeJudgement = function() {
    var conf, dataUrl, el, img;
    conf = getConfidence();
    el = conf > 0.49 ? ".likes" : ".dislikes";
    dataUrl = localStorage.getItem("imageData");
    img = localStorage.getItem("LastImage");
    return $("<div class='row'>").append('<img src="' + dataUrl + '" class="col-lg-6" >').append('<img src="' + img + '"  class="col-lg-6" >').prependTo(el);
  };

  getConfidence = function() {
    var dislikes, likes;
    likes = parseInt(localStorage.getItem("currentImageLikes"));
    dislikes = parseInt(localStorage.getItem("currentImageDislikes"));
    return likes / (likes + dislikes);
  };

  getTotal = function() {
    var dislikes, likes;
    likes = parseInt(localStorage.getItem("currentImageLikes"));
    dislikes = parseInt(localStorage.getItem("currentImageDislikes"));
    return likes + dislikes;
  };

}).call(this);
